apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: iotorg
      defaultBucket: iot
    secureJsonData:
      token: mytoken123
    isDefault: true
