[server]
# Domain will be set via GF_SERVER_DOMAIN env var
# For soak: http://iotdash-soak.eastus.cloudapp.azure.com/grafana/
# For local: http://localhost:3000/grafana/
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
domain = localhost
